import { FIR, Accused, Victim, Witness, Hotspot, Transaction, Evidence, AuditLog } from './api';

export const mockFirs: FIR[] = [
  {
    id: "KSP/2026/04431",
    title: "Phishing & Sim Swap Bank Fraud",
    description: "Victim reported sudden loss of cellular signal, followed by three unauthorized transactions totaling ₹15,00,000 from accounts.",
    type: "Cyber Crime",
    status: "Open",
    severity: "High",
    date: "2026-06-15",
    time: "14:30",
    location: "Indiranagar",
    district: "Bengaluru Urban",
    policeStation: "Indiranagar Station",
    modusOperandi: "Sim Swap and Phishing",
    accusedIds: ["A-1193", "A-1204"],
    victimIds: ["V-5001"],
    witnessIds: ["W-6001"],
    evidenceIds: ["E-8001", "E-8002"]
  },
  {
    id: "KSP/2026/04108",
    title: "Domestic Assault and Extortion",
    description: "Victim subjected to physical abuse and demands for dowry. Accused threatened victim's family with public defamation.",
    type: "Women Safety",
    status: "Pending Investigation",
    severity: "Medium",
    date: "2026-05-20",
    time: "09:00",
    location: "Kuchela Layout",
    district: "Mysuru",
    policeStation: "Mysuru East Station",
    modusOperandi: "Physical Abuse & Blackmail",
    accusedIds: ["A-1102"],
    victimIds: ["V-5002"],
    witnessIds: ["W-6002"],
    evidenceIds: ["E-8003"]
  },
  {
    id: "KSP/2026/03977",
    title: "Shell Company Investment Fraud",
    description: "Luring middle-income victims into investing in dummy agricultural startups promising 40% yearly returns. Money routed through shell accounts.",
    type: "Financial Crimes",
    status: "Solved",
    severity: "High",
    date: "2026-04-12",
    time: "11:15",
    location: "Lalbagh Road",
    district: "Bengaluru Urban",
    policeStation: "Wilson Garden Station",
    modusOperandi: "Shell Company Ponzi Scheme",
    accusedIds: ["A-1193", "A-1105"],
    victimIds: ["V-5003", "V-5004"],
    witnessIds: ["W-6003"],
    evidenceIds: ["E-8004"]
  },
  {
    id: "KSP/2026/02991",
    title: "Gold Smuggling Syndicate",
    description: "Interception of passenger carrying 4.5kg of undeclared gold paste in custom linings at airport transit. Linked to cross-border networks.",
    type: "Financial Crimes",
    status: "Open",
    severity: "High",
    date: "2026-03-05",
    time: "23:45",
    location: "Devanahalli Airport Road",
    district: "Bengaluru Rural",
    policeStation: "Devanahalli Airport Station",
    modusOperandi: "Body Concealment & Smuggling",
    accusedIds: ["A-1204"],
    victimIds: [],
    witnessIds: ["W-6004"],
    evidenceIds: ["E-8005"]
  },
  {
    id: "KSP/2026/01882",
    title: "Two-Wheeler Theft Ring",
    description: "Organized gang stealing parked two-wheelers outside metro stations using duplicate master keys and dismantling for spare parts.",
    type: "Theft",
    status: "Solved",
    severity: "Low",
    date: "2026-02-18",
    time: "18:10",
    location: "Yeshwanthpur Metro Station",
    district: "Bengaluru Urban",
    policeStation: "Yeshwanthpur Station",
    modusOperandi: "Master Key Theft",
    accusedIds: ["A-1088"],
    victimIds: ["V-5005"],
    witnessIds: ["W-6005"],
    evidenceIds: ["E-8006"]
  },
  {
    id: "KSP/2026/05120",
    title: "AI Voice Cloning Extortion Scam",
    description: "Fraudsters cloned voice of senior doctor using AI tools to extort ₹8,50,000 from elderly parents claiming emergency ICU surgery.",
    type: "Cyber Crime",
    status: "Open",
    severity: "High",
    date: "2026-07-02",
    time: "16:20",
    location: "Peenya Industrial Area",
    district: "Bengaluru Urban",
    policeStation: "Peenya Station",
    modusOperandi: "Deepfake AI Voice Deepfake",
    accusedIds: ["A-1193"],
    victimIds: ["V-5001"],
    witnessIds: ["W-6001"],
    evidenceIds: ["E-8001"]
  },
  {
    id: "KSP/2026/05211",
    title: "Hawala Money Trail Interception",
    description: "Intercepted illegal cash transit of ₹45,00,000 packaged in seafood containers near port terminal.",
    type: "Financial Crimes",
    status: "Pending Investigation",
    severity: "High",
    date: "2026-07-10",
    time: "03:15",
    location: "Old Port Area",
    district: "Mangaluru",
    policeStation: "Mangaluru North Station",
    modusOperandi: "Hawala Cargo Bypass",
    accusedIds: ["A-1204"],
    victimIds: [],
    witnessIds: ["W-6004"],
    evidenceIds: ["E-8005"]
  },
  {
    id: "KSP/2026/05309",
    title: "Nighttime Highway Armed Robbery",
    description: "Armed gang blocked NH-48 highway near Tumakuru bypass with boulders and robbed three commercial trucks at gunpoint.",
    type: "Theft",
    status: "Open",
    severity: "High",
    date: "2026-07-14",
    time: "02:40",
    location: "NH-48 Tumakuru Bypass",
    district: "Tumakuru",
    policeStation: "Tumakuru Town Station",
    modusOperandi: "Highway Blockade & Robbery",
    accusedIds: ["A-1088"],
    victimIds: ["V-5005"],
    witnessIds: ["W-6005"],
    evidenceIds: ["E-8006"]
  },
  {
    id: "KSP/2026/05412",
    title: "Fake Stamp Paper Forgery Syndicate",
    description: "Seized counterfeit government revenue stamps worth ₹2.4 Crores printed in illegal press near Hubballi outskirts.",
    type: "Financial Crimes",
    status: "Solved",
    severity: "High",
    date: "2026-07-18",
    time: "11:00",
    location: "Gokul Road Industrial Estate",
    district: "Hubballi-Dharwad",
    policeStation: "Hubballi South Station",
    modusOperandi: "Off-Grid Counterfeit Offset Printing",
    accusedIds: ["A-1105"],
    victimIds: [],
    witnessIds: ["W-6003"],
    evidenceIds: ["E-8004"]
  },
  {
    id: "KSP/2026/05490",
    title: "Stalking & Harassment via Spoofed Apps",
    description: "Accused created multiple fake social profiles and sent threatening messages to college student in Mysuru.",
    type: "Women Safety",
    status: "Solved",
    severity: "Medium",
    date: "2026-07-19",
    time: "19:30",
    location: "Saraswathipuram",
    district: "Mysuru",
    policeStation: "Saraswathipuram Station",
    modusOperandi: "Cyber Stalking & VOIP Spoofing",
    accusedIds: ["A-1102"],
    victimIds: ["V-5002"],
    witnessIds: ["W-6002"],
    evidenceIds: ["E-8003"]
  },
  {
    id: "KSP/2026/05501",
    title: "Commercial Property Arson & Threat",
    description: "Extortion gang threw petrol bombs into textile warehouse after owner refused monthly protection fees.",
    type: "Theft",
    status: "Open",
    severity: "High",
    date: "2026-07-20",
    time: "01:10",
    location: "Banthwal Main Road",
    district: "Mangaluru",
    policeStation: "Banthwal Station",
    modusOperandi: "Extortion Arson Attack",
    accusedIds: ["A-1204"],
    victimIds: ["V-5001"],
    witnessIds: ["W-6004"],
    evidenceIds: ["E-8005"]
  },
  {
    id: "KSP/2026/05540",
    title: "Illegal Synthetic Drugs Factory Raid",
    description: "Narcotics Wing raided secluded farmhouse in Belagavi producing synthetic amphetamines destined for metropolitan clubs.",
    type: "Financial Crimes",
    status: "Solved",
    severity: "High",
    date: "2026-07-21",
    time: "04:50",
    location: "Khanapur Road",
    district: "Belagavi",
    policeStation: "Belagavi Rural Station",
    modusOperandi: "Farmhouse Lab Synthesis",
    accusedIds: ["A-1193"],
    victimIds: [],
    witnessIds: ["W-6001"],
    evidenceIds: ["E-8002"]
  },
  {
    id: "KSP/2026/05588",
    title: "Crypto Wallet Ransomware Attack",
    description: "Local hospital network locked by ransomware demanding 5 Bitcoins. Critical patient records compromised.",
    type: "Cyber Crime",
    status: "Pending Investigation",
    severity: "High",
    date: "2026-07-21",
    time: "08:15",
    location: "Kalaburagi Ring Road",
    district: "Kalaburagi",
    policeStation: "Kalaburagi City Station",
    modusOperandi: "Spear Phishing Ransomware",
    accusedIds: ["A-1193"],
    victimIds: ["V-5003"],
    witnessIds: ["W-6003"],
    evidenceIds: ["E-8001"]
  },
  {
    id: "KSP/2026/05602",
    title: "ATM Skimming & PIN Harvest",
    description: "Skimmer devices and pinhole micro cameras recovered from unmanned ATM kiosk in Udupi temple complex.",
    type: "Cyber Crime",
    status: "Open",
    severity: "Medium",
    date: "2026-07-21",
    time: "10:30",
    location: "Temple Square",
    district: "Udupi",
    policeStation: "Udupi Town Station",
    modusOperandi: "Overlay Magnetic Skimmer",
    accusedIds: ["A-1088"],
    victimIds: ["V-5004"],
    witnessIds: ["W-6005"],
    evidenceIds: ["E-8006"]
  }
];

export const mockAccused: Accused[] = [
  {
    id: "A-1193",
    name: "Ramesh Kumar @ Bullet Ramesh",
    age: 34,
    gender: "Male",
    education: "Undergraduate (Dropped out)",
    occupation: "Unemployed / Independent Contractor",
    socioEconomic: "Middle Class",
    district: "Bengaluru Urban",
    address: "Peenya Industrial Area, 4th Cross, Bengaluru",
    modusOperandi: "Specializes in SIM swap fraud, phishing infrastructure, and local extortion.",
    riskScore: 88,
    riskLevel: "High",
    priorArrests: 4,
    criminalHistory: ["2023: Sim Swap Fraud", "2024: Cyber Extortion"],
    bankAccounts: ["HDFC ****9012", "SBI ****4411"],
    networkTies: ["A-1204 (Hawala Facilitator)"]
  },
  {
    id: "A-1204",
    name: "Vikram Shetty @ Gulf Vikki",
    age: 41,
    gender: "Male",
    education: "Diploma in Logistics",
    occupation: "Import-Export Logistics Agent",
    socioEconomic: "Upper Middle Class",
    district: "Mangaluru",
    address: "Banthwal Main Road, Mangaluru",
    modusOperandi: "Routes illicit funds through hawala channels and custom cargo loopholes.",
    riskScore: 79,
    riskLevel: "High",
    priorArrests: 2,
    criminalHistory: ["2022: Gold Smuggling", "2025: Wire Fraud"],
    bankAccounts: ["ICICI ****1129"],
    networkTies: ["A-1193 (Phishing Syndicate)"]
  },
  {
    id: "A-1102",
    name: "Suresh Gowda",
    age: 29,
    gender: "Male",
    education: "B.Com",
    occupation: "Real Estate Broker",
    socioEconomic: "Lower Middle Class",
    district: "Mysuru",
    address: "Kuchela Layout, Mysuru East",
    modusOperandi: "Domestic coercion, land forgery intimidation, and digital harassment.",
    riskScore: 64,
    riskLevel: "Medium",
    priorArrests: 1,
    criminalHistory: ["2024: Land Dispute Intimidation"],
    bankAccounts: ["Canara ****8820"],
    networkTies: []
  },
  {
    id: "A-1105",
    name: "Anand Murthy @ Auditor Anand",
    age: 48,
    gender: "Male",
    education: "Chartered Accountant (Suspended)",
    occupation: "Financial Consultant",
    socioEconomic: "Upper Class",
    district: "Bengaluru Urban",
    address: "Jayanagar 4th Block, Bengaluru",
    modusOperandi: "Creates multi-layered shell entities, dummy board directors, and Ponzi schemes.",
    riskScore: 72,
    riskLevel: "High",
    priorArrests: 3,
    criminalHistory: ["2021: Shell Company Fraud", "2024: Tax Evasion"],
    bankAccounts: ["Axis ****3301", "Federal ****9018"],
    networkTies: ["A-1193"]
  },
  {
    id: "A-1088",
    name: "Manjunath @ Chotta Manja",
    age: 26,
    gender: "Male",
    education: "SSLC",
    occupation: "Mechanic Assistant",
    socioEconomic: "Low Income",
    district: "Bengaluru Urban",
    address: "Yeshwanthpur Slum Clearance Board Quarter, Bengaluru",
    modusOperandi: "Master key two-wheeler theft, vehicle identification number tampering.",
    riskScore: 45,
    riskLevel: "Medium",
    priorArrests: 5,
    criminalHistory: ["2022: Vehicle Theft", "2023: Vehicle Theft"],
    bankAccounts: ["Kotak ****5512"],
    networkTies: []
  }
];

export const mockVictims: Victim[] = [
  { id: "V-5001", name: "Ananth Narayan", age: 52, gender: "Male", socioEconomic: "Middle Class", education: "Graduate", address: "Indiranagar, Bengaluru", caseId: "KSP/2026/04431" },
  { id: "V-5002", name: "Sunitha Gowda", age: 26, gender: "Female", socioEconomic: "Lower Middle Class", education: "High School", address: "Mysuru East, Mysuru", caseId: "KSP/2026/04108" },
  { id: "V-5003", name: "Dr. K.V. Rao", age: 61, gender: "Male", socioEconomic: "Upper Middle Class", education: "Post Graduate", address: "Wilson Garden, Bengaluru", caseId: "KSP/2026/03977" },
  { id: "V-5004", name: "Meenakshi Sundaram", age: 48, gender: "Female", socioEconomic: "Middle Class", education: "Graduate", address: "Jayanagar, Bengaluru", caseId: "KSP/2026/03977" },
  { id: "V-5005", name: "Suhas Hegde", age: 28, gender: "Male", socioEconomic: "Middle Class", education: "B.E. IT", address: "Yeshwanthpur, Bengaluru", caseId: "KSP/2026/01882" }
];

export const mockWitnesses: Witness[] = [
  { id: "W-6001", name: "Prakash Raj", age: 39, gender: "Male", statement: "Observed two men installing suspicious equipment near mobile tower distribution box.", reliabilityScore: 85, caseId: "KSP/2026/04431" },
  { id: "W-6002", name: "Kamala Devi", age: 54, gender: "Female", statement: "Heard loud screaming and glass breaking from neighbor's residence at 08:30 AM.", reliabilityScore: 90, caseId: "KSP/2026/04108" },
  { id: "W-6003", name: "Nitin Hegde", age: 31, gender: "Male", statement: "Was offered 40% returns by Auditor Anand at their corporate office in Jayanagar.", reliabilityScore: 78, caseId: "KSP/2026/03977" },
  { id: "W-6004", name: "Captain R. D'Souza", age: 45, gender: "Male", statement: "Noticed unmanifested cargo containers loaded onto fishing trawler under cover of fog.", reliabilityScore: 92, caseId: "KSP/2026/02991" },
  { id: "W-6005", name: "Girish K.", age: 24, gender: "Male", statement: "Saw suspect using a modified screwdriver to unlock motorcycle near metro gate.", reliabilityScore: 82, caseId: "KSP/2026/01882" }
];

export const mockHotspots: Hotspot[] = [
  { id: "H-1", area: "Peenya Industrial Area", district: "Bengaluru Urban", lat: 13.032, lng: 77.514, density: 94, primaryType: "Cyber Crime & Sim Swap", riskLevel: "High", recommendation: "Deploy Mobile Cyber Patrol & Station Extra ANPR Cameras" },
  { id: "H-2", area: "Indiranagar 100ft Road", district: "Bengaluru Urban", lat: 12.978, lng: 77.640, density: 82, primaryType: "Phishing & Financial Fraud", riskLevel: "High", recommendation: "Increase Banking Kiosk Audits & Patrol" },
  { id: "H-3", area: "Old Port Area", district: "Mangaluru", lat: 12.865, lng: 74.838, density: 88, primaryType: "Hawala & Gold Smuggling", riskLevel: "High", recommendation: "Joint Maritime Checkpost & Container Scanning" },
  { id: "H-4", area: "Devaraja Market", district: "Mysuru", lat: 12.308, lng: 76.653, density: 85, primaryType: "Extortion & Women Harassment", riskLevel: "High", recommendation: "Deploy Pink Beat Patrol & CCTV Monitoring" },
  { id: "H-5", area: "Gokul Road", district: "Hubballi-Dharwad", lat: 15.364, lng: 75.123, density: 76, primaryType: "Forgery & Property Disputes", riskLevel: "Medium", recommendation: "Revenue Verification Patrol Unit" }
];

export const mockTransactions: Transaction[] = [
  { id: "TX-9011", sender: "Ramesh Kumar (A-1193)", receiver: "Shell Corp - FinTech Infra Ltd", amount: 1500000, timestamp: "2026-06-15 14:45", riskScore: 92, location: "Bengaluru", status: "Flagged" },
  { id: "TX-9012", sender: "Vikram Shetty (A-1204)", receiver: "Overseas Cargo Logistics LLC", amount: 4500000, timestamp: "2026-07-10 03:20", riskScore: 88, location: "Mangaluru", status: "Intercepted" },
  { id: "TX-9013", sender: "Anand Murthy (A-1105)", receiver: "Agri Grow Capital Dummy A/C", amount: 2400000, timestamp: "2026-04-12 11:30", riskScore: 95, location: "Bengaluru", status: "Frozen" },
  { id: "TX-9014", sender: "Unknown Cyber Actor", receiver: "Offshore Wallet 0x8F...421", amount: 850000, timestamp: "2026-07-02 16:30", riskScore: 91, location: "Bengaluru", status: "Under Audit" }
];

export const mockEvidence: Evidence[] = [
  { id: "E-8001", title: "Cloned SIM Card & VOIP Logs", type: "Digital Artifact", caseId: "KSP/2026/04431", uploadedAt: "2026-06-16", chainOfCustodyHash: "0x892a...f712", officer: "Inspector K. Sharma", chainOfCustody: ["Collected at Scene", "Digital Vault Verified"] },
  { id: "E-8002", title: "Interception CDR Call Transcripts", type: "Audio Transcript", caseId: "KSP/2026/04431", uploadedAt: "2026-06-16", chainOfCustodyHash: "0x341b...90ac", officer: "Inspector K. Sharma", chainOfCustody: ["CDR Uploaded", "Hash Signed"] },
  { id: "E-8003", title: "Recorded Audio Threats & Messages", type: "Audio File", caseId: "KSP/2026/04108", uploadedAt: "2026-05-21", chainOfCustodyHash: "0x77c2...11ef", officer: "Sub-Inspector L. Gowda", chainOfCustody: ["Evidence Sealed"] },
  { id: "E-8004", title: "Sealed Bank Ledger & Shell Leases", type: "Document", caseId: "KSP/2026/03977", uploadedAt: "2026-04-14", chainOfCustodyHash: "0x129a...bb89", officer: "DySP R. Venkatesh", chainOfCustody: ["Seized from Office", "Court Audit Logged"] },
  { id: "E-8005", title: "Gold Paste Packets (4.5kg Sealed)", type: "Physical Evidence", caseId: "KSP/2026/02991", uploadedAt: "2026-03-06", chainOfCustodyHash: "0x661d...44e0", officer: "Customs Officer S. Rao", chainOfCustody: ["Airport Interception", "Malkhana Custody"] },
  { id: "E-8006", title: "Master Keys & Dismantled Parts", type: "Physical Tool", caseId: "KSP/2026/01882", uploadedAt: "2026-02-19", chainOfCustodyHash: "0x9900...ab71", officer: "Head Constable M. Patil", chainOfCustody: ["Recovered from Shed"] }
];

export const mockAuditLogs: AuditLog[] = [
  { id: "LOG-101", user: "Officer Kumar", role: "Investigator", action: "Queried Case KSP/2026/04431", timestamp: "2026-07-21 11:20", ip: "10.14.2.88" },
  { id: "LOG-102", user: "Supervisor Rao", role: "Supervisor", action: "Approved Wire Interception TX-9012", timestamp: "2026-07-21 10:45", ip: "10.14.2.12" },
  { id: "LOG-103", user: "Analyst Priya", role: "Analyst", action: "Generated Statewide Hotspot Forecast", timestamp: "2026-07-21 09:30", ip: "10.14.2.45" }
];
